Fix Dockerfile paths and update build scripts

diff --git a/docker/files/firstboot/functions b/docker/files/firstboot/functions
--- a/docker/files/firstboot/functions
+++ b/docker/files/firstboot/functions
@@ -67,11 +67,11 @@ core3_clone() {
         return
     fi
 
-    msg "Setup Core3 source code.."
+    msg "Setup The-Hunted-Dev source code.."
     mkdir -vp ${HOME_DIR}/workspace
     cd ${HOME_DIR}/workspace
-    git clone --progress ${REPO_PUBLIC_URL}/Core3.git
-    cd Core3
+    git clone --progress ${REPO_PUBLIC_URL}/The-Hunted-Dev.git
+    cd The-Hunted-Dev
     echo 'MMOCoreORB/bin/scripts/managers/resource_manager_spawns.lua' >> .git/info/exclude
     git update-index --assume-unchanged MMOCoreORB/bin/scripts/managers/resource_manager_spawns.lua
     git checkout ${REPO_PUBLIC_BRANCH}
@@ -94,6 +94,16 @@ core3_mysql_setup() {
     mysql_install_db
     chown -R mysql:mysql /var/lib/mysql /var/lib/mysql/.
     /etc/init.d/mariadb start
+    mkdir -p /var/run/mysqld
+    mkdir -p /var/lib/mysql
+    chown -R mysql:mysql /var/run/mysqld
+    chown -R mysql:mysql /var/lib/mysql
+    chmod 777 /var/run/mysqld
+
+    mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
+    mysqld_safe --datadir='/var/lib/mysql' &
+    sleep 5
+
     mysql -v <<-EOF
         SET @@SESSION.SQL_LOG_BIN=0;
         DELETE FROM mysql.user WHERE user NOT IN ('mysql.sys', 'mariadb.sys', 'mysqlxsys', 'root') OR host NOT IN ('localhost') ;
@@ -107,18 +117,18 @@ core3_mysql_setup() {
         FLUSH PRIVILEGES;
 EOF
 
-    local init_sql="${HOME_DIR}/workspace/Core3/MMOCoreORB/sql/swgemu.sql"
+    local init_sql="${HOME_DIR}/workspace/The-Hunted-Dev/MMOCoreORB/sql/swgemu.sql"
 
     if [ -f "${init_sql}" ]; then
         msg "Create database from ${init_sql}"
-        core3_mysql_fix_dbname "${init_sql}" | mysql || error "Failed to run swgemu.sql" 12
+        core3_mysql_fix_dbname "${init_sql}" | mysql -uroot -p"${DBPASS}" || error "Failed to run swgemu.sql" 12
     else
         warning "Failed to find ${init_sql} file to setup the database"
     fi
 }
 
 core3_init_config() {
-    local cfg="${HOME_DIR}/workspace/Core3/MMOCoreORB/bin/conf/config-local.lua"
+    local cfg="${HOME_DIR}/workspace/The-Hunted-Dev/MMOCoreORB/bin/conf/config-local.lua"
 
     msg "Initializing ${cfg}..."
 
